name: Render main.pdf
on: push

jobs:
  render-paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: typst-community/setup-typst@v4
        with:
          cache-dependency-path: requirements.typ

      # Compile the Typst document
      - run: typst compile main.typ CV_baptiste.pdf

      # Upload the PDF as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CV_baptiste
          path: CV_baptiste.pdf
          if-no-files-found: error
          compression-level: 0

      # Deploy PDF to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: CV_baptiste.pdf
  deploy:
    needs: render-paper
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v4
